version: 2.1
jobs:
  package:
    docker:
      - image: eb129/docker-kubectl:v1.0.1
    steps:
      - checkout
      - run: scripts/helm.sh
workflows:
  package:
    jobs:
      - package:
          context: helm-charts-repository
