# Default values for incident-bot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

affinity: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

database:
  enabled: true
  password: foobar1234

envVars:
  AUTH0_DOMAIN: mydomain
  AUTO_CREATE_RCA: false
  INCIDENTS_DIGEST_CHANNEL: incidents
  INCIDENT_AUTO_GROUP_INVITE_ENABLED: false
  INCIDENT_AUTO_GROUP_INVITE_GROUP_NAME: mygroup
  INCIDENT_EXTERNAL_PROVIDERS_ENABLED: false
  INCIDENT_EXTERNAL_PROVIDERS_LIST: github
  INCIDENT_AUTO_CREATE_FROM_REACT_ENABLED: true
  INCIDENT_AUTO_CREATE_FROM_REACT_EMOJI_NAME: create-incident
  PAGERDUTY_INTEGRATION_ENABLED: false
  STATUSPAGE_INTEGRATION_ENABLED: false
  CONFLUENCE_API_URL: https://echoboomer-test.atlassian.net
  CONFLUENCE_API_USERNAME: scott@echoboomer.net
  CONFLUENCE_API_TOKEN: ElGZzkz16FQS7FOJN3Kk93B4
  CONFLUENCE_SPACE: ENGINEERIN
  CONFLUENCE_PARENT_PAGE: RCAs
  STATUSPAGE_API_KEY:
  STATUSPAGE_PAGE_ID:
  STATUSPAGE_URL:
  PAGERDUTY_API_USERNAME: me@foo.com
  POSTGRES_HOST: db
  POSTGRES_DB: incident_bot
  POSTGRES_USER: incident_bot
  POSTGRES_PASSWORD: foobar1234
  POSTGRES_PORT: 5432
  SLACK_APP_TOKEN: xapp-1-A0361A6MK2R-4040074216580-7eb70fc137889ef82f0c97b65cd682a78898074258cbf10ac79e67d42cb2e179
  SLACK_BOT_TOKEN: xoxb-495823307894-3208244938114-8gQfQg29TPQ0ZJZYcbpvc9PG
  DEFAULT_WEB_ADMIN_PASSWORD: foobar1234
  JWT_SECRET_KEY: aflksamflkfgmdslgvmweuig340g43mglrekm

healthCheck:
  enabled: true
  path: /api/v1/health
  port: 3000
  scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 1

image:
  repository: eb129/incident-bot
  pullPolicy: IfNotPresent

imagePullSecrets: []

ingress:
  enabled: true
  className: ''
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: incident-bot.echoboomer.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: incident-bot-tls
      hosts:
        - incident-bot.echoboomer.net

nodeSelector: {}

podAnnotations: {}

podDisruptionBudget:
  enabled: false
  minAvailable: 1

podSecurityContext:
  {}
  # fsGroup: 2000

replicaCount: 1

resources:
  limits:
    cpu: 1000m
    memory: 512M
  requests:
    cpu: 250m
    memory: 256M

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ''

tolerations: []
