# Default values for incident-bot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

affinity: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

database:
  enabled: false
  password:

envVars:
  AUTH0_DOMAIN: mydomain
  AUTO_CREATE_RCA: false
  INCIDENTS_DIGEST_CHANNEL: incidents
  INCIDENT_AUTO_GROUP_INVITE_ENABLED: false
  INCIDENT_AUTO_GROUP_INVITE_GROUP_NAME: mygroup
  INCIDENT_EXTERNAL_PROVIDERS_ENABLED: false
  INCIDENT_EXTERNAL_PROVIDERS_LIST: github
  INCIDENT_AUTO_CREATE_FROM_REACT_ENABLED: true
  INCIDENT_AUTO_CREATE_FROM_REACT_EMOJI_NAME: create-incident
  PAGERDUTY_INTEGRATION_ENABLED: false
  STATUSPAGE_INTEGRATION_ENABLED: false
  CONFLUENCE_API_URL:
  CONFLUENCE_API_USERNAME:
  CONFLUENCE_API_TOKEN:
  CONFLUENCE_SPACE:
  CONFLUENCE_PARENT_PAGE:
  STATUSPAGE_API_KEY:
  STATUSPAGE_PAGE_ID:
  STATUSPAGE_URL:
  PAGERDUTY_API_USERNAME:
  POSTGRES_HOST: db
  POSTGRES_DB: incident_bot
  POSTGRES_USER: incident_bot
  POSTGRES_PASSWORD:
  POSTGRES_PORT: 5432
  SLACK_APP_TOKEN:
  SLACK_BOT_TOKEN:
  DEFAULT_WEB_ADMIN_PASSWORD:
  JWT_SECRET_KEY:

healthCheck:
  enabled: true
  path: /api/v1/health
  port: 3000
  scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 1

image:
  repository: eb129/incident-bot
  pullPolicy: Always

imagePullSecrets: []

ingress:
  enabled: true
  className: ''
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: incident-bot.mydomain.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: incident-bot-tls
      hosts:
        - incident-bot.mydomain.com

nodeSelector: {}

podAnnotations: {}

podDisruptionBudget:
  enabled: false
  minAvailable: 1

podSecurityContext:
  {}
  # fsGroup: 2000

replicaCount: 1

resources:
  limits:
    cpu: 1000m
    memory: 512M
  requests:
    cpu: 250m
    memory: 256M

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ''

tolerations: []
